spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8081/
          predicates:
            - Path=/ressources/**
        - id : r2
          uri: http://localhost:8082/
          predicates:
            - Path=/reservations/**
  application:
    name: gateway-service
server:
  port: 8888
